### ISSUE TITLE
Logo is blurred

### ISSUE THREAD

**Issue by soycapitan** [BiOSS-Group/bioss-group.github.io#2]
Letters are hardly legible. Unless this is desired we should use a higher quality image.

**Comment by kdomino** [comment]
I know, I have a discussion with Natalia on it.

**Comment by jmiszczak** [comment]
I just cut out the logo from PDF. Better version coming as soon as we get vectorized version.

**Comment by NKruszewska** [comment]
It was only proposal version. If we pick something I will do vectorized version. 
Other propositions:
![image](https://user-images.githubusercontent.com/94965439/210768226-cf9c61c8-08eb-4028-8daf-06d0195f7bda.png)

**Comment by kdomino** [comment]
see [BiOSS_loga2.png](https://github.com/BiOSS-Group/bioss-group.github.io/blob/main/img/BiOSS_loga2.png)

**Comment by kdomino** [comment]
Done in ebce6788959783d4284f38d1052399a72c180d41
